### ISSUE TITLE
Protect GET endpoints

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#42]
Example: a student who isn't enrolled in CS 2500 (course id 1) tries to navigate to `khouryofficehours.com/class/1/today`. Any API requests made for this class should return with an error because they aren't enrolled in that class. Same goes for queue routes.

**Comment by willstenzel** [comment]
Has this already been covered by the `@UseGuards(JwtAuthGuard)` in our controllers?

https://github.com/sandboxnu/office-hours/blob/5247fe34dc667671a29f3b4b985a992022a3e115/packages/server/src/course/course.controller.ts#L14-L26

**Comment by willstenzel** [comment]
The issue I'm still seeing is on the frontend. When you visit a route and are unauthorized, the "Something went wrong page" flashes briefly before getting redirected to the login page. 

I think we'll want to intercept the 401 responses and redirect directly to the login page instead of doing it in the `useProfile` hook.

**Comment by willstenzel** [comment]
Oh I might have been wrong before, the `@UseGuards(JwtAuthGuard)` just checks that the user has an auth token which is registered in out system. However, as mentioned in the issue summary, we'll want to check that the user is in the particular course they are hitting the api endpoint for.
