### ISSUE TITLE
Research and scope out types of tests with Cypress

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#50]
Get a few test cases down if you can
Scaffolding for different user flows we want to test on the frontend

**Comment by willstenzel** [comment]
### What can cypress do?

Cypress is an end-to-end testing frameworks that makes automating user actions and test scenarios as easy as possible

- Can mock out api responses
- Can run on local or on deployed code

### Additional

- Unit test our components [https://github.com/bahmutov/cypress-react-unit-test](https://github.com/bahmutov/cypress-react-unit-test)
- Visual testing with Percy integration [https://github.com/percy/percy-cypress](https://github.com/percy/percy-cypress)

### What user flows should we test?

- [ ]  Login User (might not be able to do this with the admin site)
- [ ]  Navigate to queue page
- [ ]  Student - Create, Edit, Delete Question
- [ ]  TA - Update the status of a student questions

### Questions

- [ ]  Should we run tests on the Vercel PR deployment or a staging site?
- [ ]  Should we mock out the the api responses or not? Seems like for now it's best to stub the responses because it creates faster tests and isolates front end functionality
