### ISSUE TITLE
Profile photo not sized correctly in settings page on widescreen display

### ISSUE THREAD

**Issue by willstenzel** [sandboxnu/office-hours#589]
This bug was reported on a (3440 x 1440) screen.

![Capture2](https://user-images.githubusercontent.com/33739155/107830584-2c246900-6d5a-11eb-97ff-2301d9493c33.png)

**Comment by NEUDitao** [comment]
Ah I see. the `Avatar` is looking @ the screen's resolution to determine how big to make it, but the `Container` shrinks everything to 1920 * 1080 in dimensions... Ultrawide support will be tricky to say the least...

**Comment by brianyyang** [comment]
From what I can see from testing and Nicky's observations, I feel like the right way to solve this would be to make the profile settings on the right side responsive like the avatar? It seems less like the avatar is sized incorrectly rather than the first name and last name input fields are static regardless of dimensions. Will experiment sizing based off screen width b/c that's how the Avatar is being sized right now
