### ISSUE TITLE
[Mobile Friendliness] -- Implement Settings Page From Figma 

### ISSUE THREAD

**Issue by dfarooq610** [sandboxnu/office-hours#726]
Talk to Megan and implement the mobile settings page!

**Comment by nicoledanuwidjaja** [comment]
The current mobile layout is very unfriendly. Due to the profile icon popping up in the hamburger menu, it is unclear to a user on how to even reach the settings page. (See screenshots)

I think we will need to fix this entire flow so that users are able to navigate to these pages.
![image](https://user-images.githubusercontent.com/15938301/138618806-c8234c18-4405-4746-bc72-52e4d33540fd.png)
![image](https://user-images.githubusercontent.com/15938301/138618808-10483cdb-b2d7-4b26-878d-9f2e1424cf35.png)
![image](https://user-images.githubusercontent.com/15938301/138618813-15ae54f4-a5d0-4e6c-9a7e-ae107ffc84bb.png)

**Comment by dfarooq610** [comment]
This is essentially a duplicate issue #710
